---
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: rclone | Ensure rclone package
  apt:
    # deb: "https://github.com/rclone/rclone/releases/download/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-{{ arch or deb_architecture.stdout }}.deb"
    deb: "https://downloads.rclone.org/rclone-current-linux-{{ arch or deb_architecture.stdout }}.deb"
    state: present
